### ISSUE TITLE
'Stop' on jupyter notebook does not stop running solver

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#327]
This seems to be new in 1.3.* possibly just with BasicTauHybridSolver.  I suspect that our use of threads is preventing the stop from working.

**Comment by seanebum** [comment]
This issue exists only with the BasicTauHybridSolver.   It seems to be caused by the way we are using solve_ivp.  I think the best fix for this is going to be a bit of a refactor, and may be good incentive to produce a C++ powered version.

**Comment by ethangreen-dev** [comment]
Closing in favor of #662.
