### ISSUE TITLE
Improved Error Messages for incorrect strings

### ISSUE THREAD

**Issue by seanebum** [StochSS/GillesPy2#419]
It would be helpful to have a more informative error when attempting to use an improper string expression in event triggers, parameter expressions, or rule formulas.

**Comment by briandrawert** [comment]
If a model has an event, and SSACsolver is selected, then the error is:
```
Return code: 2.
Error:
make: Entering directory '/tmp/tmpvixzms0s'
g++ -c -o model.o model.cpp -c -std=c++14 -Wall -O3
g++ -c -o ssa.o ssa.cpp -c -std=c++14 -Wall -O3
g++ UserSimulation.cpp -std=c++14 -Wall -O3 -o UserSimulation model.o ssa.o
make: Leaving directory '/tmp/tmpvixzms0s'

UserSimulation.cpp: In member function ‘virtual double PropensityFunction::evaluate(unsigned int, unsigned int*)’:
UserSimulation.cpp:38:26: error: expected primary-expression before ‘)’ token
38 | return sin(1,);
```

**Comment by briandrawert** [comment]
This should not get to the compile step, should check and throw exception earlier.

**Comment by jtcooper10** [comment]
Reviving this issue from the dead to mention that the current plan is to use the expression library created in PR #582 to work for all solvers (including Python implementations) and do pre-validation on all expressions.

In addition, a possible implementation for 1.7.0 is to 1) pre-compile all expressions required by solvers, and 2) store these pre-compiled expressions in the solver object. Doing this will help mitigate runtime performance issues that parsing and validation will impose.
