### ISSUE TITLE
CPP compilation changes

### ISSUE THREAD

**Issue by seanebum** [StochSS/GillesPy2#436]
The C++ solvers should change the way they handle compilation so that objects are not being compiled every situation.  This should be compiled to a shared location and GillesPy2 should have a "cache-clear" method associated with it.

**Comment by ethangreen-dev** [comment]
I have a working implementation on the [cpp-compilation-changes](https://github.com/StochSS/GillesPy2/tree/cpp-compilation-changes) branch. Build caching brings the `test_ssa_c_solver.py` test from a runtime of 8 seconds to just 1 -- definitely a notable performance improvement.

**Comment by ethangreen-dev** [comment]
Average time of 10 `./run_coverage.sh` runs with caching disabled and enabled:
```

Run without caching: 81.62s user 6.38s system 95% cpu 1:32.43 total
Run with caching (but no cache files): 47.65s user 3.18s system 92% cpu 54.955 total
Run with caching (with cache files): 46.22s user 3.03s system 92% cpu 53.256 total
```

Undoubtedly an inaccurate testing methodology but it's indicative of the reduction in startup time.

**Comment by ethangreen-dev** [comment]
PR #520 contains a major refactor of the C++ compilation system. This issue is more relevant to the changes, so upon v1.6 this issue will be closed. 

Cached compilation is an engineering problem that I'll tackle next week. I will make and link a new issue documenting these changes.
