### ISSUE TITLE
Question about parallelism

### ISSUE THREAD

**Issue by Princeofthebow** [StochSS/GillesPy2#453]
Hi as per title I'm trying to understand how and if Gillespy2 runs in parallel.

Suppose I have a machine with N cores and I'm running a simulation for M trajectories(regardless of what solver I pick).

Is my intution correct that each of the cores runs one trajectory? If otherwise how is parallelism implemented?
From a few tests I have done I never have seen the load on all of N cores increase with the exception of 1 which I gather is the one running the calculation. How can I maximise the use of the resources I have?

![image](https://user-images.githubusercontent.com/42376336/97354292-15cace00-188d-11eb-8516-85765650831d.png)

**Comment by seanebum** [comment]
Hello Princeofthebow,

GillesPy2 by default actual runs in serial, however you can easily make it parallel using dask!  I've included  [an example notebook here](https://github.com/StochSS/GillesPy2/blob/parallelization_example_notebook/examples/AdvancedFeatures/Run%20GillesPy2%20Simulations%20in%20Parallel.ipynb), and in case you have trouble viewing the notebook on github, here's a screenshot:

![Screenshot from 2020-10-28 14-24-24](https://user-images.githubusercontent.com/22843486/97480126-62fc7d80-1929-11eb-94b2-6475fb7820d6.png)

**Comment by Princeofthebow** [comment]
Thank you very much for this. This is very useful and I think it should be put amongst the examples as I am not the only person facing similar problems. Generating a joint probaiblity distribution for the molecules requires quite a bit of data. This is especially true for Gillespy2 where the timing of the events cannot be recorded.

Do I understand correctly that for parameter scans, Sciopoe handles it?

**Comment by seanebum** [comment]
That is a good suggestion and I will definitely add it in.

Yes! Sciope is a great way to perform n-dimensional parameter scans, definitely check it out!

**Comment by Princeofthebow** [comment]
Hi Sean, thanks, that is really good news!
It would be beneficial that if the use of resources (cores) of the machine increases as per this issue, perhaps also including the time series of the events in the output could be beneficial as we previously discussed in #427 . My understanding was indeed that recording the times slows down gillespy2 a lot but by running as you can run in parallel the realisations this downside could be partially overcome.
The motivation for this stands again as per previous comment in the need to compute steady state variances and/or moment and distributions. Here are my 0.02£.I know two ways to compute stationary distributions:

- Compute the distribution(s) once you have run the system to steady state over several trajectories and using the data from the state the biochemical systems at the end of each realisation.
- Run a single very long trajectory(and due to ergodicity) compute the distribution of the percentage of total simulation time spent in a given state for each species.

For my previous paper I relied on the first method as I was computing moments(variance to be precise), but I am now using gillespy2 to compute distributions and not making use of the timing data makes is slow (before parallelism may come into play)  to compute the distribution as per each realisation I discard all the data in time. Indeed, even if I use a linearly spaced grid I am unable to compute precisely the stationary distribution as the information of how long the system has been in a given state can be coarse grained. 

Let me know what you think or if you compute the distribution in some other way that I may be missing.

**Comment by seanebum** [comment]
This is very interesting, I will definitely be discussing this with the team!
