### ISSUE TITLE
Seed or existing data?

### ISSUE THREAD

**Issue by Princeofthebow** [StochSS/GillesPy2#469]
Hi,
     I'm sorry here that I've been spamming you lately but I've been making quite a bit of use of this project for my publications as I believe it is very good software.

My problem is now the following: I would need to simulate several trajectories of a molecules where the propensity depends upon a certain exogenous signal/time series (generated possibly outside of Gillespy).

Consider for instance the following reaction network:

Z  - F -> z+1
Z  - beta1*Z -> z-1

X - Z - > X+1
X - beta2*X -> X-1

for _one realization_ of Z I would need to compute _k_ realizations of X.

In the above setting, where Z is itself generated from gillespy, can this be achieved via proper use of the random seed (i.e. apply it solely to Z)?

Moreover if I have an externally generated signal Z (for instance form an Stochastic Differential Equation simulation) can I some how make the propensity of X depend upon this time series?

These sort of problems emerge often in filtering settings and this could be a very useful feature to have.

**Comment by seanebum** [comment]
Hello again!  I'm sorry for the delayed response on this one, the team has been all over the place over the holidays!  It sounds like you have a very interesting project, and we would love to collaborate with you on this - If you are interested, I think it could be incredibly helpful to meet up regarding these questions to get a clearer vision of what is needed.  Would you be interested in doing a Google meet in the near future to discuss this further?

**Comment by Princeofthebow** [comment]
Hi sorry @seanebum for the late reply I've been overwhelmed with work!
I'm happy to Google meet anytime this week if it works for you.

**Comment by seanebum** [comment]
No problem!  Let's try to organize a time via email! My email is smatthe2@unca.edu, just let me know some times that could work for you!
