### ISSUE TITLE
SSAC and VariableSSAC solvers fail on timeout events on Windows 10

### ISSUE THREAD

**Issue by prasi372** [StochSS/GillesPy2#480]
The timeout event is passed as a signal using os.killpg, however Windows does not have the concept of process groups. So this will need to be done differently on Windows.
--
Stack Trace:

---------------------------------------------------------------------------
TimeoutExpired                            Traceback (most recent call last)
~\.conda\envs\sciope-dev\lib\site-packages\gillespy2\solvers\cpp\variable_ssa_c_solver.py in run(self, model, t, number_of_trajectories, timeout, increment, seed, debug, profile, variables, resume, **kwargs)
    285                     if timeout > 0:
--> 286                         stdout, stderr = simulation.communicate(timeout=timeout)
    287                     else:

~\.conda\envs\sciope-dev\lib\subprocess.py in communicate(self, input, timeout)
   1023             try:
-> 1024                 stdout, stderr = self._communicate(input, endtime, timeout)
   1025             except KeyboardInterrupt:

~\.conda\envs\sciope-dev\lib\subprocess.py in _communicate(self, input, endtime, orig_timeout)
   1396                 if self.stdout_thread.is_alive():
-> 1397                     raise TimeoutExpired(self.args, orig_timeout)
   1398             if self.stderr is not None:

TimeoutExpired: Command '['C:\\Users\\prash\\AppData\\Local\\Temp\\tmpkb12lr48\\UserSimulation', '-trajectories', '1', '-timesteps', '51', '-end', '50.0', '-initial_values', '100 100', '-parameters', '1 0.2763688560449993 0.0033289936847022326 3.7949439791001995', '-seed', '48295448']' timed out after 3 seconds

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~\.conda\envs\sciope-dev\lib\site-packages\gillespy2\core\model.py in run(self, solver, timeout, t, show_labels, cpp_support, **solver_args)
    822         try:
--> 823             solver_results, rc = solver.run(model=self, t=t, increment=self.tspan[-1] - self.tspan[-2],
    824                                             timeout=timeout, **solver_args)

~\.conda\envs\sciope-dev\lib\site-packages\gillespy2\solvers\cpp\variable_ssa_c_solver.py in run(self, model, t, number_of_trajectories, timeout, increment, seed, debug, profile, variables, resume, **kwargs)
    295                 except subprocess.TimeoutExpired:
--> 296                     os.killpg(simulation.pid, signal.SIGINT)  # send signal to the process group
    297                     stdout, stderr = simulation.communicate()

AttributeError: module 'os' has no attribute 'killpg'

**Comment by ethangreen-dev** [comment]
Fixed in PR #486.
