### ISSUE TITLE
Add algorithm argument to model.run

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/GillesPy2#487]
## Purpose
The algorithm argument would be used in the absence of the solver argument to narrow the scope of solvers for the get best solver function.

## Examples
- `model.run(algorithm="SSA")` would run the simulation with the most efficient SSA solver available
- `model.run(solver="NumPySSASolver", algorithm="Tau-Leaping")` would always run the NumPySSA solver regardless of the value of algorithm.

**Comment by Fin109** [comment]
Solution in PR #443

**Comment by ethangreen-dev** [comment]
Implemented in release v1.5.8
