### ISSUE TITLE
StochMLDocument.to_model() raise AttributeError

### ISSUE THREAD

**Issue by Wrede** [StochSS/GillesPy2#512]
Current AttributeError break some of the examples implemented in [Sciope.](https://github.com/StochSS/sciope/blob/master/examples/inference/vilar/StochSS_model/vilar_oscillator_AIYDNg/models/data/vilar_oscillator.xml)

model_doc = gillespy2.StochMLDocument.from_file("sciope/examples/inference/vilarStochSS_model/vilar_oscillator_AIYDNg/models/data/vilar_oscillator.xml")

model = model_doc.to_model("Vilar")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-0e929b42cb85> in <module>
      1 model_doc = gillespy2.StochMLDocument.from_file("StochSS_model/vilar_oscillator_AIYDNg/models/data/vilar_oscillator.xml")
----> 2 model = model_doc.to_model("Vilar")

~/.envs/bnn/lib/python3.8/site-packages/gillespy2/core/model.py in to_model(self, name)
   1182                             generated_rate_name]
   1183 
-> 1184                     reaction.__create_mass_action()
   1185                 except Exception as e:
   1186                     raise

AttributeError: 'Reaction' object has no attribute '_StochMLDocument__create_mass_action'

**Comment by ethangreen-dev** [comment]
Fixed in release v1.5.11
