### ISSUE TITLE
Simulating Styrene polymerization using gillespy2 

### ISSUE THREAD

**Issue by teddiclax** [StochSS/GillesPy2#537]
Good day, I am working on comparing the deterministic and stochastic trajectories of the polymerization of styrene in free radical reaction. I find it challenging to use the module. Attached is a schematics representation of the reaction. I look forward to valuable contributions. 
Thank you.
![polymerization_Eddy](https://user-images.githubusercontent.com/85592612/122488801-996c3300-cfb4-11eb-93e3-ab5c1af93306.PNG)

**Comment by briandrawert** [comment]
Thanks for your question.  Can you please provide a complete citation for the image you provided.  Then we can provide an example of how to simulate this process.

**Comment by teddiclax** [comment]
Thank you for the timely response. The above schematic was gotten from an annual journal and here is the citation :
Curteanu, Silvia. “Modeling and Simulation of Free Radical Polymerization of Styrene under Semibatch Reactor Conditions.” Open Chemistry, vol. 1, no. 1, 2003, pp. 69–90., doi:10.2478/bf02479259.

**Comment by ethangreen-dev** [comment]
Hey @teddiclax! [This notebook](https://github.com/StochSS/GillesPy2/blob/main/examples/AdvancedFeatures/KineticModelForStyrenePolymerization.ipynb) was created to illustrate your desired behavior. It's included within the GillesPy2 v1.6.0 release, so you can either download the file directly or find it in a local copy of the repository.
 
Let us know if you have any further questions, and thanks for your patience.

**Comment by teddiclax** [comment]
Thank you for the timely response . With this ,I believe I can utilize this
code to meet my need.
Should I encounter any challenge, I will reach out for assistance. once
again, thank you.

Kind regards,
Edward.

**Comment by teddiclax** [comment]
Good day.
I hope you are all doing?

Based on a research project that involves the use of the Gillespie algorithm to simulate the stochastic trajectory of the polymerization of styrene in free radicals. I tried tweaking the existing code to mimic the trajectories from the publication. All efforts proved abortive. I intend to produce simultaneously, the deterministic and stochastic trajectories in my analysis. That is a plot of the number of polymeric chains(Mn) versus time, the molecular weight of polymer (Mw )versus time, and the polydispersity index (PDI) versus time.

My major challenge is applying the gyllespy2 python3 module to this problem to produce the trajectories. The modeled kinetic set of equations from 43-56 are a set of stiff ODEs. Also, theoretically, equations 45 -47 are equated to zero making the system a differential algebraic equation(DAEs).

I am sorry for the lengthy write-up. I look forward to your urgent assistance.
_
▲
