### ISSUE TITLE
Implementation of the Vilar oscillator

### ISSUE THREAD

**Issue by Armavica** [StochSS/GillesPy2#589]
Hello,
I am confused by the implementation of the Vilar oscillator in the examples, especially by the reactions

    s_Da: Da' --θa--> Da
    s_A2: Da' --θa--> Da' + A
    s_Dr: Dr' --θr--> Dr
    s_A3: Dr' --θa--> Dr' + A

From what I understand from [this article](https://www.pnas.org/content/pnas/99/9/5988.full.pdf), I would have expected in place of these four reactions the two following ones:

    s_Da: Da' --θa--> Da + A
    s_Dr: Dr' --θr--> Dr + A

Am I correct or did I miss something?

**Comment by BryanRumsey** [comment]
Update the example notebook to fit BIOMD0000000035_url

**Comment by briandrawert** [comment]
Hi, I believe you are correct.  We will be updating our models.  Thank you for bring this to our attention.
