### ISSUE TITLE
Return values of predicted reaction fluxes

### ISSUE THREAD

**Issue by jonrkarr** [StochSS/GillesPy2#599]
Some studies examine predictions for reaction fluxes. It would be great to return these values.

We we're working with BioModels to add buttons such as "Simulate with GillesPy2", "Simulate with COPASI", etc. Some studies require this information.

**Comment by briandrawert** [comment]
Can you please clarify what is meant by reaction fluxes?  If possible, please provide a model that has this feature.

**Comment by jonrkarr** [comment]
COPASI, tellurium, VCell and others can return the rate/velocity/flux of each reaction at each time point. Here's the [corresponding method of RoadRunner](http://sys-bio.github.io/roadrunner/docs-build/PythonAPIReference/cls_ExecutableModel.html#RoadRunner.ExecutableModel.getReactionRates).

Here's a few examples of simulation experiments in BioModels which involve observables for reaction fluxes
- BIOMD0000000627
  - See curation notes: https://www.ebi.ac.uk/biomodels/BIOMD0000000627#Curation
  - The image in the curation notes reproduces Figure 3a of https://journals.sagepub.com/doi/10.1177/0271678X17693024
- BIOMD0000000477
- BIOMD0000000674
- BIOMD0000000847
