### ISSUE TITLE
Results are truncated to t=0 when initial time < 0

### ISSUE THREAD

**Issue by jonrkarr** [StochSS/GillesPy2#600]
Version: 1.6.3

When a simulation is run with initial time < 0, the returned results are truncated such that the results start at t=0. The returned results have the requested interval, but don't have the requested number of time points because the results are truncated to t=0.

**Comment by briandrawert** [comment]
- [ ] Throw an exception when initial time of simulation is not t=0. Simulation must run from t=0 to end time (must be positive).  Addressed by: #748.
- [ ] Create example to show how to change timespan to arbitrary start/end values by shifting time array.
