### ISSUE TITLE
Sometimes GillesPy2 produces results that are inconsistent with other tools

### ISSUE THREAD

**Issue by jonrkarr** [StochSS/GillesPy2#624]
Example: Model: https://github.com/biosimulators/Biosimulators_test_suite/tree/dev/examples/sbml-core/Edelstein-Biol-Cybern-1996-Nicotinic-excitation

Below are simulation runs for GillesPy2 and PySCeS. PySCeS reproduces the reported results, whereas GillesPy2 does not.
- GillesPy2/LSODA: https://run.biosimulations.org/simulations/615b569a70c4194777b44eda
- PySCeS/LSODA: https://run.biosimulations.org/simulations/615b569b70c4192619b44edd

This was also noticed by @freiburgermsu.

**Comment by briandrawert** [comment]
The links provide above return "404 Simulation run not found"

**Comment by jonrkarr** [comment]
We reset the database over the last 6 months. Current versions are at https://run.biosimulations.org/runs?try=1.

**Comment by briandrawert** [comment]
[GP2_Issue_624.zip](https://github.com/StochSS/GillesPy2/files/10282135/GP2_Issue_624.zip)
Notebook from converting the SBML.

**Comment by briandrawert** [comment]
![image](https://user-images.githubusercontent.com/1413538/209014581-01b8c364-31bc-46ae-8ec3-fb4d0929c3b2.png)

Expected output (maybe)
