### ISSUE TITLE
Continuous SDE simulations of model possible?

### ISSUE THREAD

**Issue by TorkelE** [StochSS/GillesPy2#637]
Hello,

I have wanted to try making stochastic SDE simulations (using the chemical Langevin interpretation of the model). I have read the documentations, but have not found any options. Is this possible, and if so, how do I do it?

**Comment by briandrawert** [comment]
As of v1.6.7 GillesPy2, we have a CLE solver.  Example usage here: https://github.com/StochSS/GillesPy2/blob/main/examples/AdvancedFeatures/CLE_examples_convergence.ipynb
