### ISSUE TITLE
No observables change throughout (ODE) simulation in imported SBML model

### ISSUE THREAD

**Issue by TorkelE** [StochSS/GillesPy2#640]
I have observed this in a few SBML model (the multisite2.xml.txt one attached here, with ".txt" ending added to make GitHub permit the upload). When I simulate the model using:
```python
my_model = gillespy2.core.import_SBML("multistate.xml")
%time results_ode = my_model[0].run(solver=ODESolver())
```

the simulation seems to work fine. However, the observables (species `A_P`, `A_unbound_P`, `A_bound_P`, `RLA_P`) are all identical to 0. There seems to be some problem where these are not calculated correctly? I then try another model (the multistate one). Here they are not identical to 0, but some otehr value. It seems this value is their initial condition. Basically, the observables attain their initial value, and never change. Am I doing something wrong, or are observables simply not supported?

[multisite2.xml.txt](https://github.com/StochSS/GillesPy2/files/7499094/multisite2.xml.txt)
[multistate.xml.txt](https://github.com/StochSS/GillesPy2/files/7499118/multistate.xml.txt)

**Comment by seanebum** [comment]
Hello! GillesPy2 to does not currently support observables.  One thing I did notice, however is that these parameters are governed by Assignment Rules, and we do not currently support those in the ODESolver, however those are supported in the TauHybridSolver.  If you call the model's run function without passing it a solver argument, it should detect these features for you and select the correct solver.  Try running it without the `solver=ODESolver()` argument.

**Comment by TorkelE** [comment]
Noted, and really thank you for pointing that out.

I run the same code, but with:
```
my_model = gillespy2.core.import_SBML("multistate.xml")
%time results_ode = my_model[0].run()
```
and get a solution that does look a bit different. Does this mean I am here using the `TauHybridSolver`? The solution I get looks deterministic, but `TauHybridSolver` sounds like tau leaping or some stochastic component is involved. Can I be sure whenever this will generate normal deterministic simulations of my reaction network?

**Comment by TorkelE** [comment]
(also, closing the issue because its main question has been answered)
