### ISSUE TITLE
 How to implement the "gillespy2.export_SBML" submodule

### ISSUE THREAD

**Issue by teddiclax** [StochSS/GillesPy2#663]
Good day.
Referring to the above heading, I intend to export created model with gillespy2 which has been challenging as I cannot find any documentation regarding this subject. Please, I need guidance on how to resolve this issue.

Kind regards, 
Edward.

**Comment by briandrawert** [comment]
Documentation: https://stochss.github.io/GillesPy2/classes/gillespy2.core.html#gillespy2.core.model.export_StochSS
