### ISSUE TITLE
C++ Hybrid Solver: Use reaction root-finder instead of bisection on critical Tau steps

### ISSUE THREAD

**Issue by jtcooper10** [StochSS/GillesPy2#691]
In the `TauHybridCSolver`, it is possible for an integration step to result in an invalid simulation state. The current solution is to bisect the Tau step, [re-attempt the integration step](https://github.com/StochSS/GillesPy2/blob/abee5e4cbd05bf2331cdeebc60050f8c5ab40cfa/gillespy2/solvers/cpp/c_base/tau_hybrid_cpp_solver/TauHybridSolver.cpp#L285), and repeat until either a valid Tau step is found or [an error is indicated](https://github.com/StochSS/GillesPy2/blob/abee5e4cbd05bf2331cdeebc60050f8c5ab40cfa/gillespy2/solvers/cpp/c_base/tau_hybrid_cpp_solver/TauHybridSolver.cpp#L353), in which case the simulation stops.

Ideally, an invalid Tau step should just result in the next reaction being fired directly. The [reaction root-finder](https://github.com/StochSS/GillesPy2/blob/abee5e4cbd05bf2331cdeebc60050f8c5ab40cfa/gillespy2/solvers/cpp/c_base/tau_hybrid_cpp_solver/integrator.cpp#L209) currently used by the event system can likely be repurposed for this.

**Comment by briandrawert** [comment]
Fixed in 1.7.0
