### ISSUE TITLE
C++ Hybrid Solver: Allow parameters as Rate Rule variables

### ISSUE THREAD

**Issue by jtcooper10** [StochSS/GillesPy2#692]
Currently, `Parameter` objects [are not allowed in Rate Rules](https://github.com/StochSS/GillesPy2/blob/abee5e4cbd05bf2331cdeebc60050f8c5ab40cfa/gillespy2/solvers/cpp/build/template_gen.py#L147) for the `TauHybridCSolver`. This should be allowed.

# Required Changes
- Update the template generation code to distinguish between `Parameter` and `Species` objects.
- Modify the C++ implementation of rate rules to allow parameters as targets.

**Comment by briandrawert** [comment]
[test_issue_692.zip](https://github.com/StochSS/GillesPy2/files/10281659/test_issue_692.zip)
Testing notebook
