### ISSUE TITLE
Stochastic Trajectory For The Polymerization Model Example #735

### ISSUE THREAD

**Issue by teddiclax** [StochSS/GillesPy2#736]
Thank you for the response to #735 .
Referring to your suggestion, I chose no solver for the given problem, and yet no stochasticity was produced at low copy numbers. The same occurred for " TauLeapingSolver"
![Gillespy2 image](https://user-images.githubusercontent.com/85592612/156063739-41cb3862-4211-491d-862a-f8efc7b027f1.PNG)

However, if for simplicity, arbitrary or dummy values( integers instead of floats) were assigned to the kinetic values or parameters as earlier illustrated in #537 then, there will be stochastic trajectories produced.

In addition, following the  given example for the gillespy2 module (https://stochss.github.io/GillesPy2/tutorials/tut_toggle_switch/tut_toggle_switch.html) ;
 I intend to compare the Stochastic and Deterministic trajectories.

What do I do in this case?

**Comment by briandrawert** [comment]
GillesPy2 is working correctly for the model you are using.  However, I strongly suggest you check your units.
```
# Regarding the following reaction:
#     self.add_reaction(Reaction(reactants={'M':3}, 
#                               products={'R':2}, 
#                               propensity_function="k_iterm*M*(M-1)*(M-2)"))
# Using the parameter you set:
T=(100+273);
k_iterm = 1.99*10**(6)*math.exp(-14842/T);
M=10
# Then the average time to the first reaction is:
propensity = k_iterm*M*(M-1)*(M-2)
print(f"propensity: {propensity}")
print(f"average time to first reaction: {1/propensity}")
```
propensity: 7.502809325644655e-09
average time to first reaction: 133283408.46701154

Your simulation was run from 0-20 time units, and the average time of the first reaction event is at 133283408 time units, thus the probability of the population of species 'M' ever changing in this simulation is vanishingly low.
