### ISSUE TITLE
Stochastic  Versus Deterministic Trajectory For The Polymerization Model Example  #736

### ISSUE THREAD

**Issue by teddiclax** [StochSS/GillesPy2#740]
Good day @briandrawert.
Thank you for the responses thus far. 
Referring to polymerization system #736. I have investigated the kinetic parameters (experimental values)as well its respective units:

```
# Pre-defining the kinetic parameters :
T=(90+273); # Operating temperature in degrees Kelvin,K.
R= 8.3145; #J.mol^-1.K^-1.
k_d =2.88*10**(2)*math.exp(-30390/(T*R));
k_i = 1.712*10**(15)*math.exp(-15924/(T*R));
k_iterm =20.19*math.exp(-13810/(T));
k_p= 1.10*10**(8)*math.exp(-27480/(T*R));
k_trM=3.110*10**(3)*math.exp(-5631/(T*R));
k_trS=1.968*10**(4)*math.exp(-6302/(T));
k_tc= 2.68*10**(8)*math.exp(-2084/(T*R));
k_td=0;
```

Yet, following your advice, I used the ODECSolver and SSACSolver solvers for only the initiation and propagation reactions. Expected results were obtained within microseconds for a simulation period of 60 seconds. However, as Transfer and Termination reactions are added to the previous reactions, the simulation time runs in an unending manner. I have tried using the TauHybridCSolver also to no avail.

**Comment by briandrawert** [comment]
We are unable to replicate with the information you have provided. This is most likely a problem with your model. If you believe this be a bug with our software, please provide all the information you can for us to replicate the issue.
