### ISSUE TITLE
Negative Species causes simulation error

### ISSUE THREAD

**Issue by JoshuaFisherC** [StochSS/GillesPy2#771]
Negative species cause simulation error that resets time value to origin. Easy to replicate, just make a rate rule with a t-100 with a single species to view a basic example.

**Comment by JoshuaFisherC** [comment]
![image](https://user-images.githubusercontent.com/70917271/174137433-3f5a9ef0-9311-44b0-a7b9-18aca64196b1.png)

**Comment by JoshuaFisherC** [comment]
This is the result when running with the python tau hybrid solver.

**Comment by briandrawert** [comment]
This needs a test, to check if the new implementation handles this case correctly.
