### ISSUE TITLE
Oregonator model species `P` drops significantly at around `t=3.5`

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/GillesPy2#804]
This may be the cause of #624 

## Testing
> Currently running the TauLeapingCSolver (started on May 26, 2022)
### Solvers with Error
![image](https://user-images.githubusercontent.com/44621966/171461167-82424381-38a4-4cff-b3dc-f44bdad7b71f.png)

### Solvers without Error
![image](https://user-images.githubusercontent.com/44621966/171460909-7a9f0739-ccc0-4823-bd6e-85c92c0e83d2.png)

![image](https://user-images.githubusercontent.com/44621966/171460932-db5f681f-5382-4b82-a0e7-8ca60c4a1aaf.png)

![image](https://user-images.githubusercontent.com/44621966/171460963-cfe3d551-32c2-40c5-ab86-88cbb521e8ad.png)

![image](https://user-images.githubusercontent.com/44621966/171461005-539ff69d-9db5-4d2c-bb48-5f3914173275.png)

![image](https://user-images.githubusercontent.com/44621966/171461055-8a8d6d9f-b978-4cc1-817a-1d052d70c734.png)

![image](https://user-images.githubusercontent.com/44621966/171461097-f23d9fb9-a2f8-4be0-9d57-585bbbdcffa9.png)

**Comment by briandrawert** [comment]
Probably fixed, needs testing

**Comment by BryanRumsey** [comment]
This issue was fixed in a previous release.


![Image](https://user-images.githubusercontent.com/44621966/234974805-e736d306-4f11-49d8-8359-1dbf1c677b2f.png)
