### ISSUE TITLE
Hybrid switching sensitivity may have been lost

### ISSUE THREAD

**Issue by BryanRumsey** [StochSS/GillesPy2#849]
The hybrid switching example no longer demonstrates the switching feature but the photosynthesis example still shows switching.

**Comment by briandrawert** [comment]
![image](https://user-images.githubusercontent.com/1413538/180047843-9ad154f7-f7b3-4471-bb8b-813b0ffaba3e.png)

**Comment by briandrawert** [comment]
Above shows the system NOT switching
