### ISSUE TITLE
Integration test take in excess of 6 hours, can never complete.

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#855]
https://github.com/StochSS/GillesPy2/runs/7587496261?check_suite_focus=true

Looks like the problem is both example_models and test_all_solvers.

**Comment by BryanRumsey** [comment]
This issue is not restricted to the an OS and seems to be related to changes in `fix_hybrid_switching`.  Tested locally on `develop` and tests are working.  Tested locally on `fix_hybrid_switching` and tested are taking running longer then they should.

**Comment by briandrawert** [comment]
fixed in 90c8f72e51e199d24a9daa4f29192c36d150e488
