### ISSUE TITLE
Error encountered while running simulation C++ file (return code: 3221225785)

### ISSUE THREAD

**Issue by michimiura** [StochSS/GillesPy2#951]
Hello Gillespy2 maintainers,

I have started encountering an error: 

SimulationError: argument 'solver=<gillespy2.solvers.cpp.ssa_c_solver.SSACSolver object at 0x000001B5B1604210>' to run() failed.  Reason Given: Error encountered while running simulation C++ file (return code: 3221225785)

since I installed MinGW on my computer.  Any workaround on this issue?

Best,
Michi

**Comment by briandrawert** [comment]
Hi @michimiura,

Sorry to hear you are having trouble with the C++ solvers. Sometimes there are difficulty to diagnose incompatibility with MinGW. We are working on new system that should remove these issues.  In the mean time, you can move forward with your work by using the pure-python solvers. They are just as feature complete, and in some cases faster.  You can specify a solver by passing the 'solver=' argument to the run() function, e.g.:
 ```     result = model.run(solver=gillespy2.NumPySSASolver)```

I hope this helps, please let us know if you have any further issues.

**Comment by michimiura** [comment]
Hello Brian,

Now I could see that my run finished without any errors.  Many thanks.

Michi
