### ISSUE TITLE
Time scales

### ISSUE THREAD

**Issue by chaoui-mu** [StochSS/GillesPy2#953]
Dear Gillespy2 developers,
I am currently working on the chemical reaction of water radiolysis. I am trying to input the yields at a specific time that is determined by the irradiation time. Once this is complete, I would like to continue the simulation with Gillespy2 in the homogeneous stage. However, I have encountered an issue with transitioning between time scales. I am unsure of how to maintain the end time of irradiation as the start time of Gillespy2. 

Thank you..???

**Comment by mustapha-chaoui** [comment]
Here's a corrected version of your response:

Hi @briandrawert, thank you for your prompt answer. Exactly, I'm using Gillespy2 for the second simulation stage. In the first stage, I'm using TOPAS-nBio to irradiate a water phantom and tracking the yields of irradiation with time evolution. However, TOPAS-nBio doesn't account for some reactions that occur in the homogeneous stage. In this case, I'm trying to use Gillespy2 to continue the simulation of radicals for large timescales (1000s). But for consistency, I need to continue from the TOPAS-nBio end time, which is in milliseconds, and initialize the Gillespy2 model with the yields at the end time of TOPAS-nBio. Is there a way to do this, or a methodolgy to adress this.
 Thanks again;
Mustapha
