### ISSUE TITLE
http://www.stochss.org/ URL access issue

### ISSUE THREAD

**Issue by RichardBruskiewich** [StochSS/GillesPy2#954]
There's a web link to **http://www.stochss.org/** on the [GillesPy2 package landing page](https://pypi.org/project/gillespy2/) on PyPi.org which has some kind of auth/auth constraint triggering an access error (see below). 

This seems odd situation to have on a seemingly public web site?

**Unauthorized**
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

Additionally, a 401 Unauthorized error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by briandrawert** [comment]
This has been fixed
